web:
  upload-path: D:/ueditorimg/

spring:
  datasource:
    url: jdbc:mysql://192.168.87.124:3306/exchange_of_learning_platform?useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: 123
  mvc:   #静态文件
    static-path-pattern: /static/**
  thymeleaf:
    model: HTML5
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mail:
    username: 1963342385@qq.com
    password: yqcbmwqobzcgfchj
    host: smtp.qq.com
  #ueditor
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  messages:
    basename: i18n.login


server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

#    开启驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true
